/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.edd;

import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;

/**
 *
 * @author dario
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }
    
    
    /**
     * Description: getPath es la que ejecuta el 
     * JFileChooser para determinar la ruta del 
     * archivo txt que funcionarpa como base de
     * datos 
     * 
     * @author Darío Aldana
     * 
     * @return path: string con la ruta
     */
    private String getPath(){
        JFileChooser selector = new JFileChooser(); 
        selector.showOpenDialog(null); 
        File f = selector.getSelectedFile(); 
        String path = f.getAbsolutePath();
        return path;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        loadDB = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play.setBackground(new java.awt.Color(255, 255, 204));
        play.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        play.setText("JUGAR");
        play.setToolTipText("");
        play.setAlignmentY(0.0F);
        play.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 90, 30));

        loadDB.setBackground(new java.awt.Color(255, 255, 204));
        loadDB.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        loadDB.setText("<html>CARGAR BASE DE<br>CONOCIMIENTOS</html>");
        loadDB.setToolTipText("");
        loadDB.setAlignmentY(0.0F);
        loadDB.setBorder(new javax.swing.border.MatteBorder(null));
        loadDB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loadDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDBActionPerformed(evt);
            }
        });
        getContentPane().add(loadDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 140, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Fondo safari.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void loadDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDBActionPerformed
        // TODO add your handling code here:
        StringBuilder db = new StringBuilder();
        try {
            File file = new File(getPath());
            Scanner sc = new Scanner(file);
            sc.nextLine();
            while(sc.hasNext()){
                String line = sc.nextLine();
                db.append(line);
                db.append("//");
            }
        } catch (Exception e){
            System.out.println("Error");
        }
        System.out.println("HERE");
        System.out.println(db);
    }//GEN-LAST:event_loadDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton loadDB;
    private javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables
}
